CREATE TABLE Employees(
Id INT IDENTITY(1,1) PRIMARY KEY,
FirstName NVARCHAR(50) NOT NULL,
LastName NVARCHAR(50) NOT NULL,
Email NVARCHAR(100) NOT NULL UNIQUE,
Phone NVARCHAR(20) NOT NULL,
CardID INT(50) NOT NULL,
Department INT(50) NOT NULL,
BirthDate DATE NOT NULL,
StartDate DATE NOT NULL,
ROLES INT(50) NOT NULL,
Createdate DATETIME2 DeFAULT GETDATE(),
IsActive BIT DEFAULT 1,
IsDeleted BIT DEFAULT 0

);